#define APP_NAME "Cohesion"
#define PLAYER_CNT_MAX 2
#define MAP_DIM_MAX 16
#define MAP_TIP_MAX 64
#define TILE_SIZE 20
#define ACTOR_CNT_MAX 2
#define CLONE_CNT_MAX 32
#define WALK_SPEED 80
#define TILE_BORDER_DIM 1
#define FPS_CAP 30
#define FPS_IDLE 4
#define IDLE_TIMER_MILLI 5000
// #define SHOW_TRAVELLED
#define SHOW_EFFECTS
#define LEVEL_COMPLETE_EFFECT_DURATION_MILLI 1000
#define ROTATION_EFFECT_DURATION_MILLI 250
#define ACTION_REPEAT_INTERVAL 150
#define HISTORY_EVENT_MAX 512
#define AUDIO_ENABLED
