#define APP_NAME "Cohesion"
#define MAP_DIM_MAX 16
#define MAP_TIP_MAX 64
#define TILE_SIZE 20
#define WALK_SPEED 80
#define CLONE_CNT_MAX 32
#define TILE_BORDER_DIM 1
#define FPS_CAP 30
// #define SHOW_TRAVELLED
#define LEVEL_COMPLETE_EFFECT_DURATION_MILLI 1000
#define ROTATION_EFFECT_DURATION_MILLI 250
#define AUDIO_ENABLED
